### ISSUE TITLE
Set value

### ISSUE THREAD

**Issue by Qhilm** [syssi/esphome-total-count#11]
I am tracking a meter with this, I would like to be able to set the value to the current value of the meter.

Example of how this is done with `pulse_meter`:

```yaml
api:
  services:
    - service: set_total_pulse_meter
          variables:
            new_total: int
          then:
            - pulse_meter.set_total_pulses:
                id: sensor_pulse_meter_gas
                value: !lambda 'return new_total;'
```

**Comment by syssi** [comment]
You could add the `number` entity to your YAML:

```
number:
  - platform: total_count
    total_count:
      id: my_total_count
      name: "${name} total count"
```

In this case a number entity will show up and you could enter any value manually. The entity can be updated programmatically too:

```
- number.set:
    id: my_total_count
    value: 42
```

or using a lambda:

```
auto call = id(my_total_count).make_call();
call.set_value(42);
call.perform();
```
